### ISSUE TITLE
Import by #channel

### ISSUE THREAD

**Issue by paveldoreuli** [pR0Ps/slack-to-discord#18]
Hi
It will be great to have an opportunity to import data from a certain channel. My data loading in the big channel is interrupted. Then it would be possible to upload the remaining information to a specific channel. Thank you!

**Comment by paveldoreuli** [comment]
Process interapted every time at same time(
![Screenshot 2022-10-16 at 17 11 21](https://user-images.githubusercontent.com/114866573/196040267-797d350e-92c9-46d4-9aaf-4e6d1759c6ac.png)

**Comment by pR0Ps** [comment]
This is a great suggestion, thanks.

Also, I think the issue in the screenshot will have been fixed by #17 . I switched to using urllib3 to stream the files from Slack as they're uploaded to Discord. From the partial traceback it looks like you maybe got a read timeout which should be handled more gracefully by the new system.
